//
// info.c - CGI Environment Information (using TinyCC)
//

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int main(void) {
    // 输出 HTTP 响应头
    printf("Content-Type: text/html; charset=utf-8\r\n\r\n");
    
    // 获取环境变量
    char *method = getenv("REQUEST_METHOD");
    char *query = getenv("QUERY_STRING");
    char *remote_addr = getenv("REMOTE_ADDR");
    char *user_agent = getenv("HTTP_USER_AGENT");
    char *request_uri = getenv("REQUEST_URI");
    
    // 获取当前时间
    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    char time_str[100];
    strftime(time_str, sizeof(time_str), "%Y-%m-%d %H:%M:%S", local);
    
    // 输出 HTML
    printf("<!DOCTYPE html>\n");
    printf("<html>\n");
    printf("<head>\n");
    printf("    <title>CGI Environment Info</title>\n");
    printf("    <style>\n");
    printf("        body { font-family: Arial, sans-serif; margin: 20px; background: #f9f9f9; }\n");
    printf("        .container { max-width: 900px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n");
    printf("        h1 { color: #2c3e50; border-bottom: 3px solid #e74c3c; padding-bottom: 10px; }\n");
    printf("        h2 { color: #34495e; border-left: 4px solid #3498db; padding-left: 15px; }\n");
    printf("        table { width: 100%%; border-collapse: collapse; margin: 15px 0; }\n");
    printf("        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }\n");
    printf("        th { background-color: #3498db; color: white; }\n");
    printf("        tr:hover { background-color: #f5f5f5; }\n");
    printf("        .value { font-family: 'Courier New', monospace; background: #ecf0f1; padding: 2px 5px; border-radius: 3px; }\n");
    printf("    </style>\n");
    printf("</head>\n");
    printf("<body>\n");
    printf("    <div class=\"container\">\n");
    printf("        <h1>C CGI Environment Information</h1>\n");
    printf("        <p>Generated by TinyCC at: <strong>%s</strong></p>\n", time_str);
    
    printf("        <h2>HTTP Request Information</h2>\n");
    printf("        <table>\n");
    printf("            <tr><th>Variable</th><th>Value</th></tr>\n");
    printf("            <tr><td>Request Method</td><td class=\"value\">%s</td></tr>\n", method ? method : "N/A");
    printf("            <tr><td>Request URI</td><td class=\"value\">%s</td></tr>\n", request_uri ? request_uri : "N/A");
    printf("            <tr><td>Query String</td><td class=\"value\">%s</td></tr>\n", query ? query : "N/A");
    printf("            <tr><td>Remote Address</td><td class=\"value\">%s</td></tr>\n", remote_addr ? remote_addr : "N/A");
    printf("            <tr><td>User Agent</td><td class=\"value\">%s</td></tr>\n", user_agent ? user_agent : "N/A");
    printf("        </table>\n");
    
    printf("        <h2>C Runtime Information</h2>\n");
    printf("        <table>\n");
    printf("            <tr><th>Item</th><th>Value</th></tr>\n");
    printf("            <tr><td>Compiler</td><td class=\"value\">TinyCC (Dynamic)</td></tr>\n");
    printf("            <tr><td>sizeof(int)</td><td class=\"value\">%zu bytes</td></tr>\n", sizeof(int));
    printf("            <tr><td>sizeof(long)</td><td class=\"value\">%zu bytes</td></tr>\n", sizeof(long));
    printf("            <tr><td>sizeof(void*)</td><td class=\"value\">%zu bytes</td></tr>\n", sizeof(void*));
    printf("        </table>\n");
    
    printf("        <h2>Test Query Parameters</h2>\n");
    printf("        <p>Try accessing: <strong>/info.c?name=John&age=25&city=Beijing</strong></p>\n");
    
    printf("    </div>\n");
    printf("</body>\n");
    printf("</html>\n");
    
    return 0;
}