//
// test.c - Hello World CGI in C (using TinyCC)
//

#include <stdio.h>
#include <time.h>

int main(void) {
    // 输出 HTTP 响应头
    printf("Content-Type: text/html; charset=utf-8\r\n\r\n");
    
    // 获取当前时间
    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    char time_str[100];
    strftime(time_str, sizeof(time_str), "%Y-%m-%d %H:%M:%S", local);
    
    // 输出 HTML 内容
    printf("<!DOCTYPE html>\n");
    printf("<html>\n");
    printf("<head>\n");
    printf("    <title>Hello from C CGI</title>\n");
    printf("    <style>\n");
    printf("        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }\n");
    printf("        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n");
    printf("        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }\n");
    printf("        p { color: #666; line-height: 1.6; }\n");
    printf("        .highlight { background: #ffffcc; padding: 2px 5px; border-radius: 3px; }\n");
    printf("        .timestamp { color: #3498db; font-weight: bold; }\n");
    printf("    </style>\n");
    printf("</head>\n");
    printf("<body>\n");
    printf("    <div class=\"container\">\n");
    printf("        <h1>Hello World from C CGI!</h1>\n");
    printf("        <p>This page is generated by a <span class=\"highlight\">C script</span> using <strong>TinyCC</strong>.</p>\n");
    printf("        <p>Server time: <span class=\"timestamp\">%s</span></p>\n", time_str);
    printf("        <p>This demonstrates that C code can be executed as CGI scripts dynamically!</p>\n");
    printf("    </div>\n");
    printf("</body>\n");
    printf("</html>\n");
    
    return 0;
}
